### PR TITLE
Sass snippet added

### PR DESCRIPTION
**Pull request by kolchurinvv**
Hi there!

I love the extension!
I was missing snippets for sass, so I added those and tested them as well. I've updated the README.md annotations too.

P.S. I have no idea why the `snippets/base.json` looks so crazy. All I did is just add new lines for the sass snippets.

### CODE REVIEW

**Comment by kaangokdemir** [comment]
Hello, thanks for your good feedbacks and contribution.

The reason why `base.json` looks crazy is there were no Prettier configuration. I set it right now.

Could you merge master to your branch and run `npm run pretty` before making your commit?

Thanks,

**Comment by kolchurinvv** [comment]
Hey! sorry i took a while. merged and ran the `pretty` script. Hopefully good to go now.

**Comment by kolchurinvv** [comment]
@kaangokdemir is everything ok?

**Review by kaangokdemir — CHANGES_REQUESTED** [review]
Please don't edit lock files. The changes should affect only `base.json` and `README.md`

**Comment by kolchurinvv** [comment]
I didn't notice that something got changed. i'll close this PR and submit a new copy. i feel like that's easier  at this point :)

**Pull request closed without merging**
